services:
  - type: web
    name: evergabe-rag-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn rag_fastapi:app --host 0.0.0.0 --port 8000
    plan: free
    autoDeploy: true
